In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
train=pd.read_csv('Gradient_Descent_Boston_Dataset_Train.csv')
test=pd.read_csv('Gradient_Descent_Boston_Dataset_Test.csv',header=None)

In [3]:
train.head()

,# CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Y
0,-0.407850,-0.487722,-1.266023,-0.272599,-0.576134,1.239974,0.840122,-0.520264,-0.752922,-1.278354,-0.303094,0.410571,-1.097990,37.9
1,-0.407374,-0.487722,0.247057,-0.272599,-1.016689,0.001946,-0.838337,0.336351,-0.523001,-0.060801,0.113032,0.291169,-0.520474,21.4
2,0.125179,-0.487722,1.015999,-0.272599,1.367490,-0.439699,0.687212,-0.577309,1.661245,1.530926,0.806576,-3.795795,0.891076,12.7
3,0.028304,-0.487722,1.015999,-0.272599,1.859875,-0.047918,0.801005,-0.712836,1.661245,1.530926,0.806576,-0.066050,0.215438,19.9
4,-0.412408,-0.487722,-0.969827,-0.272599,-0.913029,-0.384137,-0.834781,0.300508,-0.752922,-0.957633,0.020560,0.431074,0.029007,22.5

In [4]:
def step_gradient(points, learning_rate, m , c):
    m_slope = 0
    c_slope = 0
    M = len(points)
    x=points[:,:13]
    y=points[:,13]
    for i in range(M):
        m_slope += (-2/M)* (y[i] -np.dot(m,x[i]) - c)*x[i]
        c_slope += (-2/M)* (y[i] -np.dot(m,x[i]) - c)
    new_m = m - learning_rate*m_slope
    new_c = c - learning_rate*c_slope
    return new_m, new_c

In [5]:
def gd(points, learning_rate, num_iterations):
    m = np.zeros(13)
    c = 0
    for i in range(num_iterations):
        m, c = step_gradient(points, learning_rate, m , c)
        print(i, " Cost: ", cost(points, m, c))
    return m, c

In [6]:
def cost(points, m, c):
    total_cost = 0
    M = len(points)
    x=points[:,:13]
    y=points[:,13]
    for i in range(M):
        total_cost += (1/M)*((y[i] - np.dot(m,x[i]) - c)**2)
    return total_cost

In [7]:
def run():
    data = np.loadtxt("Gradient_Descent_Boston_Dataset_Train.csv", delimiter=",")
    learning_rate = 0.07
    num_iterations = 100
    m, c = gd(data, learning_rate, num_iterations)
    return m, c

In [430]:
m,c=run()

0  Cost:  429.4576526268162
1  Cost:  321.428333888583
2  Cost:  242.8453617763017
3  Cost:  185.3941424262082
4  Cost:  143.3162120339305
5  Cost:  112.44543467592362
6  Cost:  89.75848900977849
7  Cost:  73.05711699954048
8  Cost:  60.74011249668522
9  Cost:  51.63922699570086
10  Cost:  44.90078419730987
11  Cost:  39.90007597293278
12  Cost:  36.17933113375853
13  Cost:  33.402677352235216
14  Cost:  31.323381475790313
15  Cost:  29.7599806862762
16  Cost:  28.578864427177827
17  Cost:  27.681545360856386
18  Cost:  26.99534459930716
19  Cost:  26.466566948116185
20  Cost:  26.055494767809975
21  Cost:  25.73271189017595
22  Cost:  25.476401497547467
23  Cost:  25.270358037400058
24  Cost:  25.102523177363434
25  Cost:  24.963906746066733
26  Cost:  24.8477907676264
27  Cost:  24.74914184679079
28  Cost:  24.664177021586895
29  Cost:  24.590042745410226
30  Cost:  24.524577324988467
31  Cost:  24.466134967922848
32  Cost:  24.413455343855773
33  Cost:  24.365566791562554
34  Cost:  24.321714415857503
35  Cost:  24.28130660978851
36  Cost:  24.243875226471136
37  Cost:  24.209045870427865
38  Cost:  24.176515697421017
39  Cost:  24.146036790431292
40  Cost:  24.117403680833224
41  Cost:  24.090443954455576
42  Cost:  24.065011156336922
43  Cost:  24.040979410833337
44  Cost:  24.018239323916696
45  Cost:  23.996694845750532
46  Cost:  23.9762608540849
47  Cost:  23.956861280156623
48  Cost:  23.938427644156537
49  Cost:  23.92089790101268
50  Cost:  23.904215522274345
51  Cost:  23.888328758496595
52  Cost:  23.87319004038168
53  Cost:  23.858755487256467
54  Cost:  23.84498449916832
55  Cost:  23.831839414630867
56  Cost:  23.819285220357514
57  Cost:  23.807289302543357
58  Cost:  23.795821231680247
59  Cost:  23.78485257471215
60  Cost:  23.77435672971627
61  Cost:  23.764308779337526
62  Cost:  23.754685359998213
63  Cost:  23.74546454450998
64  Cost:  23.736625736180777
65  Cost:  23.728149572868737
66  Cost:  23.72001783971327
67  Cost:  23.712213389493044
68  Cost:  23.7047200697312
69  Cost:  23.697522655806715
70  Cost:  23.690606789439265
71  Cost:  23.683958922003672
72  Cost:  23.67756626220459
73  Cost:  23.67141672769892
74  Cost:  23.665498900306275
75  Cost:  23.65980198448754
76  Cost:  23.65431576880873
77  Cost:  23.64903059013646
78  Cost:  23.64393730033875
79  Cost:  23.639027235286676
80  Cost:  23.634292185972743
81  Cost:  23.629724371579574
82  Cost:  23.62531641434704
83  Cost:  23.62106131610087
84  Cost:  23.616952436317163
85  Cost:  23.61298347160801
86  Cost:  23.609148436524602
87  Cost:  23.605441645580893
88  Cost:  23.60185769641071
89  Cost:  23.59839145397785
90  Cost:  23.595038035764386
91  Cost:  23.591792797869655
92  Cost:  23.588651321957045
93  Cost:  23.585609402990276
94  Cost:  23.58266303770654
95  Cost:  23.57980841377629
96  Cost:  23.57704189960499
97  Cost:  23.574360034733697
98  Cost:  23.571759520800384
99  Cost:  23.569237213024824

In [431]:
test.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,2.918166,-0.487722,1.015999,-0.272599,0.365444,-1.609343,1.117494,-1.048494,1.661245,1.530926,0.806576,-1.597551,1.041062
1,-0.403392,-0.487722,0.406098,-0.272599,-1.016689,0.560412,-1.332629,1.029344,-0.637962,-0.708183,-1.135347,0.441052,-0.894738
2,-0.413178,-0.487722,0.115738,-0.272599,0.158124,-0.234548,0.288933,-0.716639,-0.982843,-0.803212,1.176466,0.441052,-0.500850
3,-0.412649,0.413589,-0.802031,-0.272599,-0.999412,-0.408356,-1.677566,1.435452,-0.637962,-0.981390,-0.765457,0.441052,-0.591963
4,-0.405882,-0.487722,-0.375976,-0.272599,-0.299707,-0.127698,-0.504068,-0.483566,-0.523001,-0.143951,1.130230,0.403663,0.048631

In [432]:
output=[]

In [449]:
test.shape
x=test.values
x.shape

(127, 13)

In [451]:
for i in range(127):
    output.append(c+np.dot(m,x[i]))

In [452]:
output

[12.134924773673974,
 28.859973172491472,
 22.407367414633754,
 24.30479827933644,
 20.949515343629457,
 2.787069574824013,
 29.766439381625414,
 24.611025264631493,
 18.782513818404023,
 23.477659267927123,
 24.238789888135848,
 17.86485408496261,
 18.196884093952413,
 21.853774406598777,
 42.57550790635184,
 24.07791408742277,
 24.473661106104128,
 27.704296174872933,
 20.42268934152825,
 31.3832249391537,
 24.13580836234453,
 24.849667307774162,
 33.871429302003875,
 36.123255712857535,
 32.200756687737595,
 16.330754472345042,
 23.30140594236736,
 33.12144189531044,
 24.778017839772403,
 33.582457954727005,
 17.08056299783231,
 26.232929722948725,
 23.4079577217527,
 25.459134409968353,
 14.995282104551183,
 29.529960218474173,
 26.182424687414745,
 20.649281045953114,
 24.209699864631613,
 9.485577392285702,
 7.967035311624755,
 28.800020474988457,
 29.632035507114168,
 20.00095156725212,
 20.329074861217826,
 2.913766717419069,
 39.53107238957947,
 25.75976570133829,
 29.988535990429163,
 16.859549746258107,
 17.77939570634132,
 40.30705034474535,
 17.635788877237616,
 21.12460784551191,
 15.778720953568612,
 21.281455500132513,
 18.47079715399024,
 23.12915740401857,
 13.831884805652864,
 17.21816774947495,
 15.175480378714763,
 29.17117925580148,
 25.302623110485552,
 25.5569314543863,
 17.05012814923161,
 17.17609972597242,
 34.61505669740465,
 17.018914502481852,
 26.766547067463335,
 22.44147114503454,
 29.457889810822056,
 26.990505708939928,
 18.048709610659486,
 5.563754000306826,
 36.35932842572408,
 25.134103660004303,
 29.704570371222175,
 26.944230075598966,
 16.155698514499697,
 32.750655019953314,
 19.356680970302783,
 22.9332079036538,
 23.071787320726212,
 8.35164493979592,
 17.389853440294324,
 29.40332882637467,
 27.104441176885658,
 5.676478872116473,
 20.84055386773974,
 20.011562251492435,
 22.12111314646576,
 20.774312516633795,
 21.15474682387379,
 13.215339998623238,
 19.908149923429903,
 26.385919866765008,
 39.95556955674175,
 18.684656073265597,
 33.39046254336927,
 26.85932842935484,
 28.44511029612243,
 22.13423387942022,
 25.583916527484785,
 31.390670114828755,
 17.23305074232674,
 26.264870208883018,
 21.72548242388261,
 36.98023691876604,
 21.947725736384413,
 16.74026743536941,
 27.771035937327678,
 -0.4245915882789397,
 14.0798918535666,
 16.016097744519897,
 35.75433125146236,
 21.179727560125023,
 21.047977950888598,
 25.230798094854727,
 22.083585422119228,
 19.09322319218807,
 13.656814426675876,
 35.14877952109931,
 23.21364478935593,
 24.70150685069228,
 18.24964368838895,
 20.967022204037995,
 15.01218669223546]

In [460]:
import numpy as np
np.savetxt("file_name.csv", output, delimiter=",", fmt='%s')